spring.datasource.url=jdbc:postgresql://localhost:5432/repvault
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

server.port=8081

api.front-end=http://localhost:5173

logging.level.org.springframework.web=DEBUG