package com.codecool.repvault.domain.entities.enums


enum class ExerciseEnum {
    // ===== Chest =====
    BARBELL_BENCH_PRESS,
    DUMBBELL_BENCH_PRESS,
    INCLINE_BENCH_PRESS,
    DECLINE_BENCH_PRESS,
    CHEST_FLY_DUMBBELL,
    PEC_DECK_MACHINE,
    CHEST_PRESS_MACHINE,
    CABLE_CROSSOVER,
    PUSH_UP,
    DIPS,

    // ===== Back =====
    PULL_UP,
    CHIN_UP,
    LAT_PULLDOWN,
    BARBELL_ROW,
    DUMBBELL_ROW,
    SEATED_CABLE_ROW,
    T_BAR_ROW,
    MACHINE_ROW,
    DEADLIFT,
    HYPEREXTENSION,

    // ===== Shoulders =====
    OVERHEAD_PRESS_BARBELL,
    OVERHEAD_PRESS_DUMBBELL,
    SHOULDER_PRESS_MACHINE,
    ARNOLD_PRESS,
    LATERAL_RAISE_DUMBBELL,
    LATERAL_RAISE_MACHINE,
    FRONT_RAISE,
    REAR_DELT_FLY,
    FACE_PULL,
    UPRIGHT_ROW,

    // ===== Arms =====
    BARBELL_BICEPS_CURL,
    DUMBBELL_BICEPS_CURL,
    HAMMER_CURL,
    PREACHER_CURL_MACHINE,
    CABLE_BICEPS_CURL,
    TRICEPS_PUSH_DOWN,
    SKULL_CRUSHER,
    OVERHEAD_TRICEPS_EXTENSION,
    TRICEPS_DIP,
    TRICEPS_EXTENSION_MACHINE,

    // ===== Legs =====
    BARBELL_SQUAT,
    FRONT_SQUAT,
    LEG_PRESS_MACHINE,
    HACK_SQUAT_MACHINE,
    LUNGES,
    LEG_EXTENSION,
    LEG_CURL,
    ROMANIAN_DEADLIFT,
    CALF_RAISE_STANDING,
    CALF_RAISE_SEATED,
    HIP_THRUST,
    GLUTE_BRIDGE,

    // ===== Core =====
    PLANK,
    SIDE_PLANK,
    CRUNCH,
    CABLE_CRUNCH,
    LEG_RAISE,
    HANGING_LEG_RAISE,
    RUSSIAN_TWIST,
    AB_WHEEL_ROLLOUT,
    BACK_EXTENSION_MACHINE,

    // ===== Cardio Machines =====
    TREADMILL,
    STATIONARY_BIKE,
    SPIN_BIKE,
    ELLIPTICAL,
    STAIR_CLIMBER,
    ROWING_MACHINE
}